docker_path: './docker'

# Number of GPUs to use
num_use_gpu: 2

# gitURL and branch of the project
git_url: 'https://github.com/tanimutomo/RetinaNet_for_ortho.git' # ex) 'https://github.com/username/pjname.git'
git_branch: 'feature/nms_check' # ex) 'master'

# project directory path in remote server
pj_root: '/home/tanimu/Project' # ex) '/home/username/Project/pjname'

# kronos copy "origin_data" dir to "data_dir"
# The path of the original data directory in the remote server
origin_data: '' # ex) '/home/username/Project/data/mnist_data'
# The path of the data directory seen from project directory
data_dir: '' # ex) 'data/'

# If you want to fix server and GPU number you use, please specify them
fix_server: 'diana' # ex) 'bacchus'
fix_gpu: [2, 3] # ex) [0, 1]

# ssh config path
ssh_config_path: '~/.ssh/config' # ex) '~/.ssh/config'
